// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/neo4j/neo4j-go-driver/v5/neo4j (interfaces: SessionWithContext)

// Package mock_session is a generated GoMock package.
package mock_session

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	neo4j "github.com/neo4j/neo4j-go-driver/v5/neo4j"
	reflect "reflect"
)

// MockSessionWithContext is a mock of SessionWithContext interface
type MockSessionWithContext struct {
	ctrl     *gomock.Controller
	recorder *MockSessionWithContextMockRecorder
}

// MockSessionWithContextMockRecorder is the mock recorder for MockSessionWithContext
type MockSessionWithContextMockRecorder struct {
	mock *MockSessionWithContext
}

// NewMockSessionWithContext creates a new mock instance
func NewMockSessionWithContext(ctrl *gomock.Controller) *MockSessionWithContext {
	mock := &MockSessionWithContext{ctrl: ctrl}
	mock.recorder = &MockSessionWithContextMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockSessionWithContext) EXPECT() *MockSessionWithContextMockRecorder {
	return m.recorder
}

// BeginTransaction mocks base method
func (m *MockSessionWithContext) BeginTransaction(arg0 context.Context, arg1 ...func(*neo4j.TransactionConfig)) (neo4j.ExplicitTransaction, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "BeginTransaction", varargs...)
	ret0, _ := ret[0].(neo4j.ExplicitTransaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BeginTransaction indicates an expected call of BeginTransaction
func (mr *MockSessionWithContextMockRecorder) BeginTransaction(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeginTransaction", reflect.TypeOf((*MockSessionWithContext)(nil).BeginTransaction), varargs...)
}

// Close mocks base method
func (m *MockSessionWithContext) Close(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close
func (mr *MockSessionWithContextMockRecorder) Close(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockSessionWithContext)(nil).Close), arg0)
}

// ExecuteRead mocks base method
func (m *MockSessionWithContext) ExecuteRead(arg0 context.Context, arg1 neo4j.ManagedTransactionWork, arg2 ...func(*neo4j.TransactionConfig)) (interface{}, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ExecuteRead", varargs...)
	ret0, _ := ret[0].(interface{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExecuteRead indicates an expected call of ExecuteRead
func (mr *MockSessionWithContextMockRecorder) ExecuteRead(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteRead", reflect.TypeOf((*MockSessionWithContext)(nil).ExecuteRead), varargs...)
}

// ExecuteWrite mocks base method
func (m *MockSessionWithContext) ExecuteWrite(arg0 context.Context, arg1 neo4j.ManagedTransactionWork, arg2 ...func(*neo4j.TransactionConfig)) (interface{}, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ExecuteWrite", varargs...)
	ret0, _ := ret[0].(interface{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExecuteWrite indicates an expected call of ExecuteWrite
func (mr *MockSessionWithContextMockRecorder) ExecuteWrite(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteWrite", reflect.TypeOf((*MockSessionWithContext)(nil).ExecuteWrite), varargs...)
}

// LastBookmarks mocks base method
func (m *MockSessionWithContext) LastBookmarks() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LastBookmarks")
	ret0, _ := ret[0].([]string)
	return ret0
}

// LastBookmarks indicates an expected call of LastBookmarks
func (mr *MockSessionWithContextMockRecorder) LastBookmarks() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LastBookmarks", reflect.TypeOf((*MockSessionWithContext)(nil).LastBookmarks))
}

// Run mocks base method
func (m *MockSessionWithContext) Run(arg0 context.Context, arg1 string, arg2 map[string]interface{}, arg3 ...func(*neo4j.TransactionConfig)) (neo4j.ResultWithContext, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1, arg2}
	for _, a := range arg3 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Run", varargs...)
	ret0, _ := ret[0].(neo4j.ResultWithContext)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Run indicates an expected call of Run
func (mr *MockSessionWithContextMockRecorder) Run(arg0, arg1, arg2 interface{}, arg3 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1, arg2}, arg3...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockSessionWithContext)(nil).Run), varargs...)
}

// executeQueryRead mocks base method
func (m *MockSessionWithContext) executeQueryRead(arg0 context.Context, arg1 neo4j.ManagedTransactionWork, arg2 ...func(*neo4j.TransactionConfig)) (interface{}, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "executeQueryRead", varargs...)
	ret0, _ := ret[0].(interface{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// executeQueryRead indicates an expected call of executeQueryRead
func (mr *MockSessionWithContextMockRecorder) executeQueryRead(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "executeQueryRead", reflect.TypeOf((*MockSessionWithContext)(nil).executeQueryRead), varargs...)
}

// executeQueryWrite mocks base method
func (m *MockSessionWithContext) executeQueryWrite(arg0 context.Context, arg1 neo4j.ManagedTransactionWork, arg2 ...func(*neo4j.TransactionConfig)) (interface{}, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "executeQueryWrite", varargs...)
	ret0, _ := ret[0].(interface{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// executeQueryWrite indicates an expected call of executeQueryWrite
func (mr *MockSessionWithContextMockRecorder) executeQueryWrite(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "executeQueryWrite", reflect.TypeOf((*MockSessionWithContext)(nil).executeQueryWrite), varargs...)
}

// getServerInfo mocks base method
func (m *MockSessionWithContext) getServerInfo(arg0 context.Context) (neo4j.ServerInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "getServerInfo", arg0)
	ret0, _ := ret[0].(neo4j.ServerInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// getServerInfo indicates an expected call of getServerInfo
func (mr *MockSessionWithContextMockRecorder) getServerInfo(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "getServerInfo", reflect.TypeOf((*MockSessionWithContext)(nil).getServerInfo), arg0)
}

// lastBookmark mocks base method
func (m *MockSessionWithContext) lastBookmark() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "lastBookmark")
	ret0, _ := ret[0].(string)
	return ret0
}

// lastBookmark indicates an expected call of lastBookmark
func (mr *MockSessionWithContextMockRecorder) lastBookmark() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "lastBookmark", reflect.TypeOf((*MockSessionWithContext)(nil).lastBookmark))
}

// legacy mocks base method
func (m *MockSessionWithContext) legacy() neo4j.Session {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "legacy")
	ret0, _ := ret[0].(neo4j.Session)
	return ret0
}

// legacy indicates an expected call of legacy
func (mr *MockSessionWithContextMockRecorder) legacy() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "legacy", reflect.TypeOf((*MockSessionWithContext)(nil).legacy))
}

// verifyAuthentication mocks base method
func (m *MockSessionWithContext) verifyAuthentication(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "verifyAuthentication", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// verifyAuthentication indicates an expected call of verifyAuthentication
func (mr *MockSessionWithContextMockRecorder) verifyAuthentication(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "verifyAuthentication", reflect.TypeOf((*MockSessionWithContext)(nil).verifyAuthentication), arg0)
}
